//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Messenger.Entites
{
    using System;
    using System.Collections.Generic;
    
    public partial class Messenger_Subscriber
    {
        public int IdUser { get; set; }
        public int IdGroup { get; set; }
        public System.DateTime DateOfSubscribe { get; set; }
    
        public virtual Messenger_Group Messenger_Group { get; set; }
        public virtual Messenger_User Messenger_User { get; set; }
    }
}
