//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Messenger.Entites
{
    using System;
    using System.Collections.Generic;
    
    public partial class Messenger_Dialog
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Messenger_Dialog()
        {
            this.Messenger_Message = new HashSet<Messenger_Message>();
        }
    
        public int Id { get; set; }
        public int IdFirstUser { get; set; }
        public int IdSecondUser { get; set; }
        public string LastMessage { get; set; }
    
        public virtual Messenger_User Messenger_User { get; set; }
        public virtual Messenger_User Messenger_User1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Messenger_Message> Messenger_Message { get; set; }
    }
}
