//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Messenger.Entites
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class user2_dbEntities1 : DbContext
    {
        public user2_dbEntities1()
            : base("name=user2_dbEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Messenger_Avatar> Messenger_Avatar { get; set; }
        public virtual DbSet<Messenger_City> Messenger_City { get; set; }
        public virtual DbSet<Messenger_Country> Messenger_Country { get; set; }
        public virtual DbSet<Messenger_Dialog> Messenger_Dialog { get; set; }
        public virtual DbSet<Messenger_Friendship> Messenger_Friendship { get; set; }
        public virtual DbSet<Messenger_Group> Messenger_Group { get; set; }
        public virtual DbSet<Messenger_Message> Messenger_Message { get; set; }
        public virtual DbSet<Messenger_Post> Messenger_Post { get; set; }
        public virtual DbSet<Messenger_SavedPost> Messenger_SavedPost { get; set; }
        public virtual DbSet<Messenger_Sticker> Messenger_Sticker { get; set; }
        public virtual DbSet<Messenger_User> Messenger_User { get; set; }
        public virtual DbSet<Messenger_Subscriber> Messenger_Subscriber { get; set; }
    }
}
